USE [master]
GO

/****** Object:  Database [BlogCapstone]    Script Date: 11/24/2015 2:32:21 PM ******/
CREATE DATABASE [BlogCapstone]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogCapstone', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\BlogCapstone.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BlogCapstone_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\BlogCapstone_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BlogCapstone] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogCapstone].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlogCapstone] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlogCapstone] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlogCapstone] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlogCapstone] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlogCapstone] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlogCapstone] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlogCapstone] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlogCapstone] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlogCapstone] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlogCapstone] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlogCapstone] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlogCapstone] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlogCapstone] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlogCapstone] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlogCapstone] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlogCapstone] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlogCapstone] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlogCapstone] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlogCapstone] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlogCapstone] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlogCapstone] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlogCapstone] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlogCapstone] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlogCapstone] SET  MULTI_USER 
GO

ALTER DATABASE [BlogCapstone] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlogCapstone] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlogCapstone] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlogCapstone] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BlogCapstone] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlogCapstone] SET  READ_WRITE 
GO

