USE [BlogCapstone]
GO

/****** Object:  Table [dbo].[HashTags]    Script Date: 11/27/2015 11:22:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HashTags](
	[HashTagID] [int] IDENTITY(1,1) NOT NULL,
	[HashName] [varchar](50) NULL,
 CONSTRAINT [PK_HashTags] PRIMARY KEY CLUSTERED 
(
	[HashTagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

